patreon: hipersayanx
ko_fi: hipersayanx
liberapay: hipersayanx
custom: ["https://www.paypal.me/WebcamoidDonations", "https://commerce.coinbase.com/checkout/3a58265f-a7fd-482a-b8ec-f4c9db129a83", "https://gist.github.com/hipersayanX/0d575fc7b9b36a2e9817027fb50258bd"]
