mac_task:
  matrix:
    - name: MacOS Sonoma (14.0)
      macos_instance:
        image: ghcr.io/cirruslabs/macos-sonoma-base:latest
      env:
        UPLOAD: 0
    - name: MacOS Ventura (13.0)
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      env:
        UPLOAD: 0
    - name: MacOS Monterrey (12.0)
      macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-base:latest
      env:
        UPLOAD: 0
  env:
    GITHUB_TOKEN: ENCRYPTED[fa47530508b5b9a63cbf1a9b4b9b2741c01c2f430b5ef0b39319fe7c1cd4cb285cf5e0c2ed5aa1bf990adb6200bcc742]
    HOMEBREW_PATH: /opt/homebrew
    NJOBS: 4
  env:
    only_if: ${CIRRUS_TAG} == ""
    DAILY_BUILD: 1
  env:
    only_if: ${CIRRUS_TAG} != ""
    DAILY_BUILD: 0
  macos_instance:
    cpu: 2
    memory: 4G
  timeout_in: 60m
  install_script:
    - chmod +x ports/ci/mac/install_deps.sh
    - ./ports/ci/mac/install_deps.sh
  script:
    - chmod +x ports/ci/mac/build.sh
    - ./ports/ci/mac/build.sh
  deploy_script:
    - chmod +x ports/ci/mac/deploy.sh
    - ./ports/ci/mac/deploy.sh
  upload_script:
    - chmod +x ports/ci/mac/upload.sh
    - ./ports/ci/mac/upload.sh
