name: Mac

on: [push, pull_request]

env:
  NJOBS: 4

jobs:
  build:
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - os: macos-13
           architecture: x64
           upload: 0
         - os: macos-12
           architecture: x64
           upload: 0
         - os: macos-11
           architecture: x64
           upload: 1
         # - os: macos-13
         #   architecture: arm64
         #   upload: 0
         # - os: macos-12
         #   architecture: arm64
         #   upload: 0
         # - os: macos-11
         #   architecture: arm64
         #   upload: 1
    runs-on: ${{ matrix.os }}
    env:
      UPLOAD: ${{ matrix.upload }}
      ARCHITECTURE: ${{ matrix.architecture }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        chmod +x ports/ci/mac/install_deps.sh
        ./ports/ci/mac/install_deps.sh
    - name: Release Build
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/mac/build.sh
        ./ports/ci/mac/build.sh
    - name: Release Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/mac/deploy.sh
        ./ports/ci/mac/deploy.sh
    - name: Daily Build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/mac/build.sh
        ./ports/ci/mac/build.sh
    - name: Daily Deploy
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/mac/deploy.sh
        ./ports/ci/mac/deploy.sh
    - name: Release Upload
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      with:
        files: packages/mac/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Daily Build Upload
      uses: softprops/action-gh-release@v1
      if: ${{ !startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      with:
        body: "${{ github.event.head_commit.message }} (commit: ${{ github.sha }})"
        prerelease: true
        files: packages/mac/*
        name: Daily Build
        tag_name: daily-build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
