name: Windows MSYS

on: [push, pull_request]

env:
  NJOBS: 4

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - compiler: gcc
         - compiler: clang
    env:
      COMPILER: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          ccache
          clang
          cmake
          git
          make
          pkgconf
          python3
          mingw-w64-x86_64-binutils
          mingw-w64-i686-binutils
          mingw-w64-x86_64-cmake
          mingw-w64-i686-cmake
          mingw-w64-x86_64-pkgconf
          mingw-w64-i686-pkgconf
    - name: Build
      run: ./ports/ci/windows-msys/build.sh
    - name: Deploy
      run: ./ports/ci/windows-msys/deploy.sh
